language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

notifications:
  email: false

branches:
  only:
    - master

install:
  - npm install
  - npm install --save-dev

cache:
  directories:
    - node_modules

before_script:
  - "sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm test
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls --verbose
  
jobs:
  include:
    - node_js: "8.11.3"
      env: NODE8=true
