language: node_js
branches:
  only:
    - master

install:
  - npm install

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls --verbose
